config/routes.rb
Rails.application.routes.draw do
  resources :websites
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/website.rb
class Website < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  before_action :set_website, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token
  # GET /websites or /websites.json
  def index
    @websites = Website.all
  end

  # GET /websites/1 or /websites/1.json
  def show
  end

  # GET /websites/new
  def new
    @website = Website.new
  end

  # GET /websites/1/edit
  def edit
  end

  # POST /websites or /websites.json
  def create
    @website = Website.new(website_params)

    respond_to do |format|
      if @website.save
        format.html { redirect_to website_url(@website), notice: "Website was successfully created." }
        format.json { render :show, status: :created, location: @website }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /websites/1 or /websites/1.json
  def update
    respond_to do |format|
      if @website.update(website_params)
        format.html { redirect_to website_url(@website), notice: "Website was successfully updated." }
        format.json { render :show, status: :ok, location: @website }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /websites/1 or /websites/1.json
  def destroy
    @website.destroy

    respond_to do |format|
      format.html { redirect_to websites_url, notice: "Website was successfully destroyed." }
      format.json { render json: Website.all, status: :ok }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_website
      @website = Website.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def website_params
      params.require(:website).permit(:title, :body, :link. :id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mypage</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/websites/_form.html.erb
<%= form_with(model: website) do |form| %>
  <% if website.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(website.errors.count, "error") %> prohibited this website from being saved:</h2>

      <ul>
        <% website.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.label :link, style: "display: block" %>
    <%= form.text_field :link %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/websites/_website.html.erb
<div id="<%= dom_id website %>">
  <p>
    <strong>Title:</strong>
    <%= website.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= website.body %>
  </p>

  <p>
    <strong>Link:</strong>
    <%= website.link %>
  </p>

</div>

app/views/websites/edit.html.erb
<h1>Editing website</h1>

<%= render "form", website: @website %>

<br>

<div>
  <%= link_to "Show this website", @website %> |
  <%= link_to "Back to websites", websites_path %>
</div>

app/views/websites/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Websites</h1>

<div id="websites">
  <% @websites.each do |website| %>
    <%= render website %>
    <p>
      <%= link_to "Show this website", website %>
    </p>
  <% end %>
</div>

<%= link_to "New website", new_website_path %>

app/views/websites/new.html.erb
<h1>New website</h1>

<%= render "form", website: @website %>

<br>

<div>
  <%= link_to "Back to websites", websites_path %>
</div>

app/views/websites/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @website %>

<div>
  <%= link_to "Edit this website", edit_website_path(@website) %> |
  <%= link_to "Back to websites", websites_path %>

  <%= button_to "Destroy this website", @website, method: :delete %>
</div>